### ISSUE TITLE
[BUG] The drive stats table isn't aligned properly

### ISSUE THREAD

**Issue by m-rtijn** [FredrikAugust/server-status-remake#6]
"Mount point" is above the "percentage used", and there's nothing above the mount mounts

**Comment by FredrikAugust** [comment]
picture..

**Comment by m-rtijn** [comment]
http://i.imgur.com/VgeO59j.png

**Comment by m-rtijn** [comment]
Fixed in commit 4a552a52a15f46f38684580886ab3459091c1e15
