### ISSUE TITLE
[BUG] The Temp hour graph only shows 3 points

### ISSUE THREAD

**Issue by m-rtijn** [FredrikAugust/server-status-remake#7]
as shown in this picture: http://i.imgur.com/sQBwdKO.png

I'd like there to be 12 or 24 points

**Comment by FredrikAugust** [comment]
do you have more than 3 hours?

**Comment by m-rtijn** [comment]
Yes. it has been running since ~11:00

**Comment by m-rtijn** [comment]
And now it only shows 16:00, 17:00, 18:00

**Comment by m-rtijn** [comment]
woops, misclicked.

**Comment by FredrikAugust** [comment]
post the output from db.temp.find({})

**Comment by FredrikAugust** [comment]
working on rewriting the entire minute/hour/day functions

**Comment by FredrikAugust** [comment]
Fixed in commit a6984291a17813fd408c3914d7dcdf8560ada797. Currently only on dev branch.
