### ISSUE TITLE
[BUG] Minute temp has only 22 dots

### ISSUE THREAD

**Issue by m-rtijn** [FredrikAugust/server-status-remake#8]
I'd rather have 60.

**Comment by FredrikAugust** [comment]
Not happening :-1: That will be the most cluttered shit you'll ever see.

**Comment by m-rtijn** [comment]
It was ~80 before you changed it, I liked it that way.

**Comment by FredrikAugust** [comment]
Still not happening.

**Comment by m-rtijn** [comment]
:(
