### ISSUE TITLE
[BUG] In commit f822fb480563204de113eea39489ac7dd89a76ab , the average minute, hour and day temp data are broken.

### ISSUE THREAD

**Issue by m-rtijn** [FredrikAugust/server-status-remake#9]
The averages in minute are between 2 and 5, (2.6, 3.2, 3.9 5.3)

The averages in hour are between 0 and 0.9 and there are only 4 points

The daily average is 0.

Please note that this is the temp graph we're talking about, which shouldn't include such low numbers. The realtime graph is still correct.

EDIT: load averages are also broken.

**Comment by FredrikAugust** [comment]
know issue.

**Comment by FredrikAugust** [comment]
temp rollback

**Comment by FredrikAugust** [comment]
This has been fixed in commit addeb2964d55a304a32b6b6739db51e26, or some other commit. Point is; **it's fixed**.
